import "server-only";
import { getLlmConfig } from "@/lib/llm/env";
import { resolveLlmTask } from "@/lib/llm/provider-registry";
import type { DebateTranscriptEntry } from "@/lib/data/types";

const MAX_TRANSCRIPT_ITEMS = 36;

export type OpponentReplyRequest = {
  topicTitle: string;
  opponentName: string;
  userRole?: "pro" | "con";
  transcript: DebateTranscriptEntry[];
};

export type JudgeDebateRequest = {
  topicTitle: string;
  debateFormat?: "wsda";
  transcript: DebateTranscriptEntry[];
};

export type JudgeDebateOutput = {
  winner: "pro" | "con";
  confidence: number;
  rationale: string;
  feedback: string;
  quote: string;
  scores: {
    clarity: number;
    evidence: number;
  };
};

function clampText(value: string, maxLen: number): string {
  const v = value.trim();
  if (v.length <= maxLen) return v;
  return `${v.slice(0, maxLen - 3)}...`;
}

function renderTranscript(entries: DebateTranscriptEntry[]): string {
  return entries
    .slice(-MAX_TRANSCRIPT_ITEMS)
    .map((entry) => `${entry.speaker}: ${entry.text}`)
    .join("\n");
}

function parseJsonFromModel(raw: string): Record<string, unknown> {
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    const match = raw.match(/\{[\s\S]*\}/);
    if (!match) throw new Error("Model did not return JSON.");
    return JSON.parse(match[0]) as Record<string, unknown>;
  }
}

function toBoundedScore(value: unknown, fallback: number): number {
  if (typeof value !== "number" || Number.isNaN(value)) return fallback;
  const rounded = Math.round(value * 10) / 10;
  return Math.min(5, Math.max(0, rounded));
}

export async function generateOpponentReply(
  input: OpponentReplyRequest,
): Promise<string> {
  const { provider, model } = resolveLlmTask("opponent");
  const userSide = input.userRole === "con" ? "Con" : "Pro";
  const opponentSide = userSide === "Pro" ? "Con" : "Pro";
  const messages = [
    {
      role: "system" as const,
      content:
        "You are an in-character debate opponent. Reply with exactly one short argument paragraph (2-4 sentences), no markdown, no bullet points, no prefacing.",
    },
    {
      role: "user" as const,
      content: [
        `Topic: ${input.topicTitle}`,
        `You are ${input.opponentName}, side ${opponentSide}.`,
        `The user is side ${userSide}.`,
        "Continue from the transcript and provide the next persuasive response:",
        renderTranscript(input.transcript),
      ].join("\n\n"),
    },
  ];

  try {
    const response = await provider.generate({
      model,
      temperature: 0.8,
      maxTokens: 260,
      messages,
    });
    return clampText(response.text, 700);
  } catch (primaryError) {
    const cfg = getLlmConfig();
    // If custom opponent model fails, retry once with DeepSeek's stable default chat model.
    if (cfg.opponentModel !== "deepseek-chat") {
      const retry = await provider.generate({
        model: "deepseek-chat",
        temperature: 0.8,
        maxTokens: 260,
        messages,
      });
      return clampText(retry.text, 700);
    }
    throw primaryError;
  }
}

export async function judgeDebateAndFeedback(
  input: JudgeDebateRequest,
): Promise<JudgeDebateOutput> {
  const { provider, model } = resolveLlmTask("judge");
  const response = await provider.generate({
    model,
    temperature: 0.2,
    maxTokens: 900,
    jsonMode: "json_object",
    messages: [
      {
        role: "system",
        content:
          "You are a neutral debate judge. Return strict JSON only. Evaluate argument quality and choose one winning side.",
      },
      {
        role: "user",
        content: [
          `Topic: ${input.topicTitle}`,
          `Format: ${input.debateFormat === "wsda" ? "WSDA" : "Standard"}`,
          "Transcript:",
          renderTranscript(input.transcript),
          "Return JSON with keys winner, confidence, rationale, feedback, quote, scores.",
          'winner must be "pro" or "con".',
          "confidence is a number 0-1.",
          "scores is an object with numeric clarity and evidence in range 0-5.",
          "feedback should be 2-4 sentences and actionable.",
          "quote should be one memorable sentence.",
        ].join("\n\n"),
      },
    ],
  });

  const parsed = parseJsonFromModel(response.text);
  const winner = parsed.winner === "con" ? "con" : "pro";
  const confidenceRaw =
    typeof parsed.confidence === "number" && Number.isFinite(parsed.confidence)
      ? parsed.confidence
      : 0.65;
  const confidence = Math.min(1, Math.max(0, confidenceRaw));
  const scores = (parsed.scores as Record<string, unknown> | undefined) ?? {};

  return {
    winner,
    confidence,
    rationale: clampText(String(parsed.rationale ?? "Decision generated by AI judge."), 480),
    feedback: clampText(
      String(
        parsed.feedback ??
          "Maintain clear claim-warrant-impact structure and reinforce each point with direct evidence.",
      ),
      900,
    ),
    quote: clampText(String(parsed.quote ?? "A strong case wins when claims meet proof."), 220),
    scores: {
      clarity: toBoundedScore(scores.clarity, 3.5),
      evidence: toBoundedScore(scores.evidence, 3.5),
    },
  };
}
